/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hardware_Hardware */

#ifndef _Included_hardware_Hardware
#define _Included_hardware_Hardware
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hardware_Hardware
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hardware_Hardware_getJniString
  (JNIEnv *, jobject);

/*
 * Class:     hardware_Hardware
 * Method:    openWiegand
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hardware_Hardware_openWiegand
  (JNIEnv *, jobject);

/*
 * Class:     hardware_Hardware
 * Method:    readWiegand
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hardware_Hardware_readWiegand
  (JNIEnv *, jobject);

/*
 * Class:     hardware_Hardware
 * Method:    closeWiegand
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hardware_Hardware_closeWiegand
  (JNIEnv *, jobject);

/*
 * Class:     hardware_Hardware
 * Method:    openWatchdog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hardware_Hardware_openWatchdog
  (JNIEnv *, jobject);

/*
 * Class:     hardware_Hardware
 * Method:    ioctlWatchdog
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_hardware_Hardware_ioctlWatchdog
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hardware_Hardware
 * Method:    closeWatchdog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hardware_Hardware_closeWatchdog
  (JNIEnv *, jobject);

/*
 * Class:     hardware_Hardware
 * Method:    openSerialPort
 * Signature: (Ljava/lang/String;JII)I
 */
JNIEXPORT jint JNICALL Java_hardware_Hardware_openSerialPort
  (JNIEnv *, jobject, jstring, jlong, jint, jint);

/*
 * Class:     hardware_Hardware
 * Method:    writeSerialPort
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_hardware_Hardware_writeSerialPort
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     hardware_Hardware
 * Method:    readSerialPort
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_hardware_Hardware_readSerialPort
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     hardware_Hardware
 * Method:    select
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_hardware_Hardware_select
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     hardware_Hardware
 * Method:    closeSerialPort
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_hardware_Hardware_closeSerialPort
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
